openapi: 3.0.3
info:
  title: Multiplayer Sudoku API
  version: 1.0.0
  description: REST API for multiplayer Sudoku game with real-time room management

servers:
  - url: /api
    description: Next.js API routes

paths:
  # ==================== Player Management ====================
  /player/session:
    post:
      summary: Create or retrieve player session
      description: Creates a new guest session or retrieves existing session from localStorage token
      tags: [Player]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
                  description: Existing session ID from localStorage (optional)
                displayName:
                  type: string
                  minLength: 2
                  maxLength: 20
              required: [displayName]
      responses:
        '200':
          description: Session created or retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerSession'
        '400':
          description: Invalid input

  /player/profile:
    get:
      summary: Get current player profile
      tags: [Player]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Player profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Player'
        '401':
          description: No valid session

    patch:
      summary: Update player display name
      tags: [Player]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  minLength: 2
                  maxLength: 20
              required: [displayName]
      responses:
        '200':
          description: Profile updated
        '400':
          description: Invalid input

  /player/history:
    get:
      summary: Get player's game history
      tags: [Player]
      security:
        - sessionAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Game history list
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      $ref: '#/components/schemas/GameHistoryItem'
                  total:
                    type: integer

  # ==================== Authentication (Optional) ====================
  /auth/register:
    post:
      summary: Register new user account
      description: Convert guest to registered user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                displayName:
                  type: string
                sessionId:
                  type: string
                  description: Existing guest session to link
              required: [email, password, displayName]
      responses:
        '201':
          description: User registered
        '400':
          description: Invalid input
        '409':
          description: Email already exists

  /auth/login:
    post:
      summary: Login to existing account
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerSession'
        '401':
          description: Invalid credentials

  /auth/logout:
    post:
      summary: Logout current user
      tags: [Auth]
      security:
        - sessionAuth: []
      responses:
        '200':
          description: Logged out

  # ==================== Room Management ====================
  /rooms:
    post:
      summary: Create a new game room
      tags: [Room]
      security:
        - sessionAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                difficulty:
                  type: string
                  enum: [easy, medium, hard]
                  default: medium
                maxPlayers:
                  type: integer
                  minimum: 2
                  maximum: 4
                  default: 4
      responses:
        '201':
          description: Room created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '401':
          description: No valid session

  /rooms/{code}:
    get:
      summary: Get room details
      tags: [Room]
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z0-9]{6}$'
      responses:
        '200':
          description: Room details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '404':
          description: Room not found

  /rooms/{code}/join:
    post:
      summary: Join an existing room
      tags: [Room]
      security:
        - sessionAuth: []
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Joined room
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        '400':
          description: Room is full or game already started
        '404':
          description: Room not found

  /rooms/{code}/leave:
    post:
      summary: Leave current room
      tags: [Room]
      security:
        - sessionAuth: []
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Left room

  /rooms/{code}/start:
    post:
      summary: Start the game (host only)
      tags: [Room]
      security:
        - sessionAuth: []
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Game started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameStart'
        '400':
          description: Not enough players or not host
        '404':
          description: Room not found

  # ==================== Game ====================
  /games/{roomCode}/progress:
    get:
      summary: Get current player's game progress
      tags: [Game]
      security:
        - sessionAuth: []
      parameters:
        - name: roomCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Player progress
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayerProgress'

    patch:
      summary: Update player's board (save progress)
      tags: [Game]
      security:
        - sessionAuth: []
      parameters:
        - name: roomCode
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentBoard:
                  type: string
                  pattern: '^[0-9]{81}$'
              required: [currentBoard]
      responses:
        '200':
          description: Progress saved

  /games/{roomCode}/validate:
    post:
      summary: Validate a cell entry
      tags: [Game]
      security:
        - sessionAuth: []
      parameters:
        - name: roomCode
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                row:
                  type: integer
                  minimum: 0
                  maximum: 8
                col:
                  type: integer
                  minimum: 0
                  maximum: 8
                value:
                  type: integer
                  minimum: 1
                  maximum: 9
              required: [row, col, value]
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  isCorrect:
                    type: boolean
                  conflicts:
                    type: array
                    description: Array of conflicting cell positions
                    items:
                      type: object
                      properties:
                        row:
                          type: integer
                        col:
                          type: integer

  /games/{roomCode}/complete:
    post:
      summary: Submit completed puzzle
      tags: [Game]
      security:
        - sessionAuth: []
      parameters:
        - name: roomCode
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                finalBoard:
                  type: string
                  pattern: '^[1-9]{81}$'
              required: [finalBoard]
      responses:
        '200':
          description: Completion recorded
          content:
            application/json:
              schema:
                type: object
                properties:
                  isCorrect:
                    type: boolean
                  completionTime:
                    type: integer
                    description: Milliseconds from game start
                  rank:
                    type: integer
        '400':
          description: Solution incorrect

  /games/{roomCode}/give-up:
    post:
      summary: Give up on current game
      tags: [Game]
      security:
        - sessionAuth: []
      parameters:
        - name: roomCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Marked as gave up

  /games/{roomCode}/results:
    get:
      summary: Get game results (leaderboard)
      tags: [Game]
      parameters:
        - name: roomCode
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Game results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameResults'
        '400':
          description: Game not finished yet

components:
  securitySchemes:
    sessionAuth:
      type: apiKey
      in: header
      name: X-Session-ID

  schemas:
    PlayerSession:
      type: object
      properties:
        sessionId:
          type: string
        playerId:
          type: string
        displayName:
          type: string
        isGuest:
          type: boolean

    Player:
      type: object
      properties:
        id:
          type: string
        displayName:
          type: string
        isGuest:
          type: boolean
        stats:
          type: object
          properties:
            gamesPlayed:
              type: integer
            gamesWon:
              type: integer
            averageTime:
              type: integer
            bestTime:
              type: integer

    Room:
      type: object
      properties:
        code:
          type: string
        hostPlayerId:
          type: string
        players:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              displayName:
                type: string
              isReady:
                type: boolean
              isConnected:
                type: boolean
        status:
          type: string
          enum: [waiting, playing, finished]
        settings:
          type: object
          properties:
            difficulty:
              type: string
            maxPlayers:
              type: integer

    GameStart:
      type: object
      properties:
        puzzle:
          type: string
          description: 81-char initial board
        startTime:
          type: integer
          description: Unix timestamp (ms) when game starts

    PlayerProgress:
      type: object
      properties:
        currentBoard:
          type: string
        mistakesCount:
          type: integer
        status:
          type: string
          enum: [playing, completed, gave_up]
        completionTime:
          type: integer
          nullable: true

    GameResults:
      type: object
      properties:
        roomCode:
          type: string
        difficulty:
          type: string
        rankings:
          type: array
          items:
            type: object
            properties:
              rank:
                type: integer
              playerId:
                type: string
              displayName:
                type: string
              completionTime:
                type: integer
                nullable: true
              mistakesCount:
                type: integer
              status:
                type: string
                enum: [completed, gave_up, playing]

    GameHistoryItem:
      type: object
      properties:
        roomCode:
          type: string
        difficulty:
          type: string
        playersCount:
          type: integer
        rank:
          type: integer
        completionTime:
          type: integer
          nullable: true
        didComplete:
          type: boolean
        playedAt:
          type: string
          format: date-time
